#!/bin/bash

# Create a role named example-dot-com which allows subdomains.
vault write pki_int/roles/example-dot-com \
     allowed_domains="${domain}" \
     allow_subdomains=true \
     max_ttl="720h"
