#!/bin/bash

# Enable the pki secrets engine at the pki path.
vault secrets enable pki

# Tune the pki secrets engine to issue certificates with a maximum time-to-live (TTL) of 87600 hours.
vault secrets tune -max-lease-ttl=87600h pki

# Generate the root certificate and save the certificate in CA_cert.crt.
vault write -field=certificate pki/root/generate/internal \
     common_name="${domain}" \
     ttl=87600h > CA-${domain}.crt

# Configure the CA and CRL URLs.
vault write pki/config/urls \
     issuing_certificates="$VAULT_ADDR/v1/pki/ca" \
     crl_distribution_points="$VAULT_ADDR/v1/pki/crl"
